### ISSUE TITLE
cmake build outdated?

### ISSUE THREAD

**Issue by mihaiserban** [anuragsoni/restless#9] opened 2016-09-03 06:21 UTC
I've installed libcurl before building the library. The output library has no symbols of libcurl. Is it possible the cmakelists are outdated and restless is not linked to libcurl?

-- Found CURL: /usr/local/lib/libcurl.a (found version "7.50.1") 
-- Set CURL_FOUND to TRUE.
-- Set CURL_LIBRARIES to /usr/local/lib/libcurl.a.
-- Set CURL_INCLUDE_DIRS to /usr/local/include.
-- Configuring done
-- Generating done

**Comment by anuragsoni** [comment] 2016-09-03 17:26
Hello, I just tried to build this again (i'm on a linux system) and the cmake build seems fine to me. 

Looking at the documentation for CMake's 'target link libraries', nothing obvious comes to mind. I'm open to suggestions about improving the cmake setup though!

**Comment by anuragsoni** [comment] 2016-09-10 18:05
@mihaiserban I will close this issue as I can't reproduce this. If you still have problems, feel free to open a new issue with steps to reproduce.

**Closed as completed by anuragsoni** 2016-09-10 18:05 UTC
